[en]
  title = "Bogdan Cioată"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[ro]
  title = "Bogdan Cioată"
  languageName = "Română"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/ro"
