[[main]]
  identifier = "despre"
  name = "despre"
  url = "about"
  weight = 1

[[main]]
  identifier = "blog"
  name = "blog"
  url = "archive"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "galerie"
  url = "gallery"
  weight = 3

[[main]]
  identifier = "posts"
  name = "postari"
  url = "posts"
  weight = 4